version: 2.1

# Machine to use
# orb is a code snippet that contains several scrits ready to use
#     node is a machine with node.js and package managers (like npm) and other scripts
#     heroku is a hosting server
# See https://circleci.com/docs/orb-intro/?section=configuration
orbs:
  node: circleci/node@5.0.2
#  heroku: circleci/heroku@1.2.6

# Entry point: List of job and execution order
workflows:
  test_my_app:
    jobs:
      - test
      - analysis
#      - deploy

# Each job, see workflows list
jobs:
  # First job: run jest to execute unit tests
  # Note it either needs to find Package.json at root or "app-dir". See https://circleci.com/developer/orbs/orb/circleci/node
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn jest
          name: Run tests

  # Second job: static analysis. Check syntax, style, etc.
  analysis:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn eslint src/*.js
          name: Run linter
          

