version: 2.1

# Machine to use
# orb contains node.js and package managers (like npm)
# heroku contains a lot of optimizations for circleci
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

# Entry point: List of job and execution order
workflows:
  test_my_app:
    jobs:
      - test
      - analysis

# Each job, see workflows list
jobs:
  # First job: run jest to execute unit tests
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: jest
      - run:
          command: jest
          name: Run tests
  # Second job: static analysis. Check syntax, style, etc.
  analysis:
    executor: node/default
    steps:
      - node/install-packages:
          pkg-manager: eslint
      - run:
          command: npx eslint *.js
          name: Run linter


