name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: make
      run: gcc test/test.c -o test/test.o
    - name: debug
      run: ls -R
    - name: run
      run: bash test/test.o
