name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: make
      run: git submodule update --init --recursive; ls -R; gcc test/test.c -o test/test.o; chmod +x test/test.o; gcc test/test_bdd.c -o test/test_bdd.o; chmod + test/test_bdd.o
    - name: debug
      run: ls -R
    - name: run
      run: test/test.o; test/test_bdd.o
#https://github.com/marketplace/actions/testforest-dashboard
    - name: Create test summary
      uses: test-summary/action@dist
      with:
        paths: test/unit_test_result.tap
        output: test/test-summary.md
      if: always()
    - name: Upload test summary
      uses: actions/upload-artifact@v3
      with:
        name: test-summary
        path: test/test-summary.md
      if: always()
