name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: make
      run: git submodule update; ls -R; gcc test/test.c -o test/test.o; chmod +x test/test.o; gcc test/test_bdd.c -o test/test_bdd.o; chmod + test/test_bdd.o
    - name: debug
      run: ls -R
    - name: run
      run: test/test.o; test/test_bdd.o
