name: TestManual

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Run npm install
        run: npm install
        
      - name: Install jest
        run: npm install jest

      - name: Run tests
        working-directory: ./src
        run: |
          cd src
          jest
